### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by chernjie**
Reference: http://docs.rackspace.com/servers/api/v2/cs-devguide/content/Update_Metadata-d1e5208.html

- [x]     `rumm show metadata on server :server_id`
- [x]    `rumm show metadatum :id on server :server_id`
- [x]    `rumm create metadatum on server :server_id`
- [x]    `rumm update metadatum :id on server :server_id`
- [x]    `rumm destroy metadatum :id on server :server_id`
- [x] app/help/*.txt
- [x] index test
- [x] show test
- [x] create test
- [x] destroy test

### CODE REVIEW

**Comment by chernjie** [comment]
Currently getting the following error, some assistance would be helpful.
```bash
$ rumm create metadatum on server testserver --value testvalue --key RackTest
ArgumentError: wrong number of arguments (1 for 2..3)
$ rumm update metadatum RackTest on server testserver --value testvalue
ArgumentError: wrong number of arguments (1 for 2..3)
```

Thanks in advanced

**Comment by chernjie** [comment]
For some reason all the `nodes` test are not working
```
$ rspec spec/features/nodes_spec.rb

  An error occurred in an after hook
    NoMethodError: undefined method `[]' for nil:NilClass
    occurred at ~/workspace/rumm/spec/features/nodes_spec.rb:13:in `block (3 levels) in <top (required)>'

FFFF
```

**Comment by chernjie** [comment]
Added some test for index and show

**Comment by chernjie** [comment]
@smashwilson This feature is now ready for review :) all test pass

**Comment by smashwilson** [comment]
:+1: Excellent, thank you!

**Pull request merged**
